1
lifull-dev/bucky-core pull request #114
Opened 2024-09-10 08:37 UTC by T-Y89

2024-09-30 04:23 UTC, T-Y89 commented on lib/bucky/test_equipment/user_operation/user_operation_helper.rb
> +          alert = wait_until_helper(5, 0.1, Selenium::WebDriver::Error::NoSuchAlertError) { @driver.switch_to.alert }
https://github.com/SeleniumHQ/selenium/blob/0cd8bbc268c3735bdbe67f9f738c845514be55ff/rb/lib/selenium/webdriver/common/error.rb#L4
みてなくね？
ってなった

リリースノートが見つからない

2024-10-21 12:15 UTC, nk-ty requested changes
@T-Y89 
Thank you for the PR.
I reviewed it, please check the comments.

2024-10-21 12:15 UTC, nk-ty commented on docker-compose.dev-with-bm.yml
> +      dockerfile: Dockerfile.seleniarm
本PRではこのままでいいですが、Issue化をお願いします。

以下Issueの概要です。

デフォルトがarm(M系チップ）になってしまっているので、特定の開発環境に依存してしまっています。
依存をわかりやすいdocker-composeファイル名にするか、Intel/Apple問わず動作する汎用的な設定にするかが必要だと思います。

2024-10-21 12:15 UTC, nk-ty commented on lib/bucky/test_equipment/verifications/service_verifications.rb
> +          Dir.glob("#{$bucky_home_dir}/services/#{@service}/#{@device}/verifications/*.rb").sort.each do |file|
ここの修正の意図を教えて下さい！
Rubyバージョンで処理に差異があるのでしょうか？

2024-10-21 12:15 UTC, nk-ty commented on lib/bucky/utils/config.rb
> +          # p "@default_config_file: #{@default_config_file}"
```suggestion
```

2024-10-21 12:15 UTC, nk-ty commented on lib/bucky/utils/config.rb
> +          # p "@default_config_file: #{@default_config_file}"
デバッグプリントが残っているようです。

2024-10-21 12:15 UTC, nk-ty commented on system_testing/test_bucky_project/system/logs/bucky_error.log.0
このファイルはログなので削除してください！

2024-10-21 12:15 UTC, nk-ty commented on system_testing/testing_code/e2e.bats
> +  echo "$output"
デバッグプリントが残っているようなので、削除してください。

2024-10-22 02:43 UTC, T-Y89 commented on .dockerignore
> -.sample/
すみません意図してない変更でした
戻し忘れのままpushしてしまいました

2024-10-22 04:27 UTC, T-Y89 commented on lib/bucky/test_equipment/verifications/service_verifications.rb
> +          Dir.glob("#{$bucky_home_dir}/services/#{@service}/#{@device}/verifications/*.rb").sort.each do |file|
バージョンの差異ではなく、rubocopからの指摘でした
これは後で相談させてください

```bash
lib/bucky/test_equipment/verifications/service_verifications.rb:44:11: W: [Correctable] Lint/NonDeterministicRequireOrder: Sort files before requiring them.
          Dir.glob("#{$bucky_home_dir}/services/#{@service}/#{@device}/verifications/*.rb").each do |file|
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

1 file inspected, 1 offense detected, 1 offense autocorrectable

Tip: Based on detected gems, the following RuboCop extension libraries might be helpful:
  * rubocop-rake (https://rubygems.org/gems/rubocop-rake)
  * rubocop-rspec (https://rubygems.org/gems/rubocop-rspec)

You can opt out of this message by adding the following to your config (see https://docs.rubocop.org/rubocop/extensions.html#extension-suggestions for more options):
  AllCops:
    SuggestExtensions: false
```

2024-10-23 01:17 UTC, T-Y89 commented on lib/bucky/test_equipment/verifications/service_verifications.rb
> +          Dir.glob("#{$bucky_home_dir}/services/#{@service}/#{@device}/verifications/*.rb").sort.each do |file|
2.5ではsortを入れないとパフォーマンス悪化につながるらしいです
target_vertionを2.5にしていたための指摘でした

3.2を指定したらでなくなりました
https://github.com/lifull-dev/bucky-core/pull/114/commits/c809fb218d97a4a34fa50d888c29d15263cd2473

2024-10-23 02:55 UTC, nk-ty approved these changes
LGTM

2024-10-24 10:39 UTC, shouan2212 commented on Dockerfile.system-test
> +  git config --global http.sslVerify false && \
@T-Y89 
`git config --global http.sslVerify false`
ですが、L28とL43が重複しています。（２回いるかどうか分からないのでご確認お願いします）

2024-10-25 01:27 UTC, T-Y89 commented on Dockerfile.system-test
> +  git config --global http.sslVerify false && \
ナイスレビューです。不要ですね！

2024-10-25 01:29 UTC, T-Y89 commented on Dockerfile.system-test
> +# SSL検証を無効にする設定を追加
この処理が無いと以下のエラーになる

<details><summary></summary>

```
 docker compose -f docker-compose.system-test.yml up --build -d
省略
 => [bucky-core 2/7] RUN apk update &&   apk upgrade &&   apk add --update  bash   build-base   curl-dev   git   iproute2   libxml2-dev   libxslt-dev   linux  19.2s
 => ERROR [bucky-core 3/7] RUN git clone https://github.com/bats-core/bats-core.git /tmp/bats-core   && cd /tmp/bats-core   && ./install.sh /usr/local   && rm  0.2s
------
 > [bucky-core 3/7] RUN git clone https://github.com/bats-core/bats-core.git /tmp/bats-core   && cd /tmp/bats-core   && ./install.sh /usr/local   && rm -rf /tmp/bats-core:
0.168 Cloning into '/tmp/bats-core'...
0.233 fatal: unable to access 'https://github.com/bats-core/bats-core.git/': SSL certificate problem: self signed certificate in certificate chain
------
failed to solve: process "/bin/sh -c git clone https://github.com/bats-core/bats-core.git /tmp/bats-core   && cd /tmp/bats-core   && ./install.sh /usr/local   && rm -rf /tmp/bats-core" did not complete successfully: exit code: 128
```

</details>

2024-10-25 01:31 UTC, T-Y89 commented on Dockerfile.system-test
> +# SSL検証を無効にする設定を追加
@nk-ty @shouan2212 

このエラーになるのって
- Netskope
- おま環

かわかりますか？（二人の環境で再現しますか？）
もし上記に当てはまるならこの変更は取り込まない方が良さそうと思いました

2024-10-25 04:33 UTC, nk-ty commented on Dockerfile.system-test
> +# SSL検証を無効にする設定を追加
取り急ぎ実行してみたけど、同じエラーが出ました。
```
 => ERROR [bucky-core 3/7] RUN git clone https://github.com/bats-core/bats-core.git /tmp/bats-core   && cd /tmp/bats-c  0.2s
------
 > [bucky-core 3/7] RUN git clone https://github.com/bats-core/bats-core.git /tmp/bats-core   && cd /tmp/bats-core   && ./install.sh /usr/local   && rm -rf /tmp/bats-core:
0.096 Cloning into '/tmp/bats-core'...
0.149 fatal: unable to access 'https://github.com/bats-core/bats-core.git/': SSL certificate problem: self signed certificate in certificate chain
------
failed to solve: process "/bin/sh -c git clone https://github.com/bats-core/bats-core.git /tmp/bats-core   && cd /tmp/bats-core   && ./install.sh /usr/local   && rm -rf /tmp/bats-core" did not complete successfully: exit code: 128
```

2024-10-25 07:04 UTC, nk-ty requested changes
Thanks for fixing.

2024-10-25 07:04 UTC, nk-ty commented on Dockerfile.system-test
> -RUN git config --global http.sslVerify false && \
@T-Y89 
削除スべきは `git config --global http.sslVerify false` だけだと思いました！

2024-10-28 02:59 UTC, nk-ty approved these changes
LGTM about `http.sslVerify`

2024-10-29 04:22 UTC, shouan2212 approved these changes
lgtm

2024-12-09 04:21 UTC, merged